# Generated by Django 4.0.3 on 2022-04-12 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.FloatField(verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='productCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productcategory', verbose_name='category'),
        ),
    ]
