# Generated by Django 4.0.3 on 2022-03-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.FloatField(verbose_name='price')),
                ('item_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productcategory', verbose_name='category')),
            ],
        ),
    ]
